import { PlaceEntity } from './place/model.js';

export const places: PlaceEntity[] = [
	{
		id: `selfie`,
		type: 'restaurant',
		name: 'Selfie',
		site: 'https://selfiemoscow.ru/reserve.html',
		location: '',
		comment: 'Хорошее место, еда хорошая, коктейли топ',
		createdAt: new Date().getTime(),
		updatedAt: new Date().getTime(),
	},
	{
		id: `bjorn`,
		type: 'restaurant',
		name: 'Bjorn',
		site: 'https://bjorn.rest/',
		location: '',
		comment:
			'Скандинавское атмосферное место. Подробно рассказывали про блюда, интересная подача',
		createdAt: new Date().getTime(),
		updatedAt: new Date().getTime(),
	},
	{
		id: `she`,
		type: 'restaurant',
		name: 'She',
		site: 'https://she.wrf.su/',
		location: '',
		comment: 'Не вкатило, второй раз бы не пошел',
		createdAt: new Date().getTime(),
		updatedAt: new Date().getTime(),
	},
	{
		id: `munterra`,
		type: 'hooka',
		name: 'Munterra',
		site: 'https://munterra.ru/',
		location: '',
		comment: '',
		createdAt: new Date().getTime(),
		updatedAt: new Date().getTime(),
	},
	{
		id: `натахтари`,
		type: 'restaurant',
		name: 'Натахтари',
		site: 'https://www.cafenatahtari.ru/',
		location: '',
		comment: '',
		createdAt: new Date().getTime(),
		updatedAt: new Date().getTime(),
	},
];
